= start.spring.io image:https://badges.gitter.im/spring-io/initializr.svg[link="https://gitter.im/spring-io/initializr?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
:library: https://github.com/spring-io/initializr

This repository configures a {library}[Spring Initializr] instance with a custom UI
running at https://start.spring.io. The following defines are available:

* `start-client`: client-side assets
* `start-size`: server infrastructure and metadata configuration

[[build]]
== Building from Source

You need Java 1.8 and a bash-like shell.

[[building]]
=== Building

Invoke the build at the root of the project

[indent=0]
----
    $ ./mvnw clean install
----

The project also has Selenium tests that instrument the client side. In order to run them
you need first to install Firefox and the latest
https://github.com/mozilla/geckodriver[geckodriver].

Once those are installed you can run the smoke tests by enabling an extra profile:

[indent=0]
----
    $ ./mvnw verify -PsmokeTests
----


[[run-app]]
=== Running the app locally
You can easily start the app as any other Spring Boot app:

[indent=0]
----
    $ cd start-site
    $ ../mvnw spring-boot:run
----

[[run-ide]]
=== Running the app in an IDE
You should be able to import the project into your IDE with no problems. Once there you
can run the `StartApplication` from its main method and debug it. If you also need to
work on the library, adding the `initializr` project in your workspace would make sure
to reload the app whenever you make any change.

This is the recommended way to operate while you are developing the application,
especially the UI.

## Deploying to Cloud Foundry

If you are on a Mac and using https://brew.sh/[homebrew], install the Cloud Foundry
CLI:

[indent=0]
----
    $ brew install cloudfoundry-cli
----

Alternatively, download a suitable binary for your platform from
https://console.run.pivotal.io/tools[Pivotal Web Services].

You should ensure that the application name and URL (name and host values) are
suitable for your environment before running `cf push`.

First, make sure that you have <<building, built the application>>, then make sure first
that the jar has been created:

[indent=0]
----
    $ cd start-site
    $ ../mvnw package
----

Once the jar has been created, you can push the application:

[indent=0]
----
    $ cf push your-start -p target/start-site.jar
----


== License
The start.spring.io website is Open Source software released under the
https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
