name: Build Pull Request
on: pull_request

permissions:
  contents: read

jobs:
  build:
    name: Build pull request
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'spring-io/start.spring.io' }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots verify

      - name: Run metadata verification tests
        run: ./mvnw --batch-mode --update-snapshots -Pverification verify
