name: Build on Windows
permissions:
  contents: read
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          java-version-file: '.sdkmanrc'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw.cmd --batch-mode --update-snapshots --no-transfer-progress verify
        env:
          JUNIT_MAX_PARALLELISM: "1"
