name: Verification
on:
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:

jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'maven'

      - name: Cache Maven/Gradle repositories for tests
        uses: actions/cache@v4
        with:
          path: /tmp/start-spring-io-cache
          # See https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
          key: test-repositories-ubuntu-latest-${{ github.run_id }}
          restore-keys: test-repositories-ubuntu-latest

      - name: Build with Maven
        env:
          START_SPRING_IO_TMPDIR: /tmp/start-spring-io-cache
        run: ./mvnw --batch-mode --update-snapshots --activate-profiles verification verify

      - name: Send notification
        uses: ./.github/actions/send-notification
        if: always()
        with:
          webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
          run-name: ${{ format('start.spring.io (Verification) | {0}', github.ref_name) }}
